@ECHO OFF
SETLOCAL
%SYSTEMDRIVE%
ECHO %PROCESSOR_ARCHITECTURE% | FINDSTR AMD64>NUL && SET ARCH=AMD64 || SET ARCH=x86
IF %ARCH%==AMD64 SET DIRECTORY=%PROGRAMFILES(X86)%
IF %ARCH%==x86 SET DIRECTORY=%PROGRAMFILES%
CD "%DIRECTORY%"
FOR /f %%x IN (
'DIR /AD /B * ^| FINDSTR "^sox-[0-9].*$"'
) DO SET SOXDIR=%DIRECTORY%\%%x
%~D0
CD "%~DP0"
@ECHO ON
MKDIR spectrograms
FOR %%A IN (*.flac) DO "%SOXDIR%\sox.exe" "%%A" -n remix 1 spectrogram -t "%%A" -x 1000 -o "spectrograms/%%A.png"
@PAUSE